name: CI Basic Checks
on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install yamllint
      - run: yamllint .
