name: CI Basic Checks
on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *" # daily
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check YAML syntax
        run: |
          if command -v yamllint >/dev/null 2>&1; then
            yamllint .
          else
            echo "yamllint not installed; skipping"
          fi
